spring:
  application:
    name: ms-email
  datasource:
    url: jdbc:postgresql://localhost:5432/email
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    username: ${EMAIL}
    password: ${PASSWORD}
server:
  port: 0

mq:
  queues:
    ms-email: ms-email


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}