spring:
  application:
    name: ms-email
  datasource:
    url: ${URL}
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    addresses: ${RABBITMQ}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
      ssl.trust: smtp.gmail.com
    username: ${EMAIL}
    password: ${PASSWORD_EMAIL}
server:
  port: 0

mq:
  queues:
    ms-email: ${QUEUE}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}