spring:
  application:
    name: ms-gym
  datasource:
    url: jdbc:postgresql://localhost:5432/gymsys_test
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0

api:
  security:
    token:
      secret: secret@!@!@

eureka:
  instance:
    instance-id= ${spring:application:name}:${spring:application:instance_id:${random:value}}