spring:
  application:
    name: ms-gym

eureka:
  instance:
    instance-id= ${spring:application:name}:${spring:application:instance_id:${random:value}}

api:
  security:
    token:
      secret: secret@!@!@